changelog:
  categories:
    - label: "breaking change"
      title: "Breaking Changes"
    - label: "new feature"
      title: "New Features"
    - label: "bug"
      title: "Bug Fixes"
    - label: "documentation"
      title: "Documentation"
    - label: "*"
      title: "Other Changes"